import prisma from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { CreditCard, Calendar, CheckCircle2, Clock, Info } from "lucide-react";
import { redirect } from "next/navigation";

export default async function StudentPaymentsPage() {
  const session = await getServerSession(authOptions);
  
  if (!session?.user?.id) redirect("/student/login");

  const profile = await prisma.studentProfile.findUnique({
    where: { userId: session.user.id },
    include: { payments: { orderBy: { createdAt: "desc" } } }
  });

  if (!profile) return <div>Profile not found</div>;

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div>
        <h2 className="text-2xl font-bold text-slate-800 font-outfit">Rent & Payments</h2>
        <p className="text-slate-500 mt-1">View your billing history and pending invoices.</p>
      </div>

      <div className="bg-blue-50 border border-blue-100 text-blue-800 p-4 rounded-2xl flex gap-3 text-sm">
        <Info size={20} className="shrink-0 text-blue-500 mt-0.5" />
        <p>
          <strong>Notice:</strong> Online payments are currently processed externally via UPI/Bank Transfer. 
          Please contact Admin on <span className="font-semibold">7229976031</span> to clear pending dues and have your invoice updated.
        </p>
      </div>

      <div className="bg-white rounded-3xl border border-slate-100 shadow-sm overflow-hidden">
        {profile.payments.length === 0 ? (
          <div className="p-16 text-center">
            <CreditCard size={48} className="text-slate-300 mx-auto mb-4" />
            <h3 className="text-lg font-bold text-slate-800">No payment invoices</h3>
            <p className="text-slate-500 mt-1">Invoices generated by admin will appear here.</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm whitespace-nowrap">
              <thead className="bg-slate-50 text-slate-600 font-semibold border-b border-slate-200">
                <tr>
                  <th className="px-6 py-4">Billing Month</th>
                  <th className="px-6 py-4">Amount</th>
                  <th className="px-6 py-4">Status</th>
                  <th className="px-6 py-4">Ref/Date</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {profile.payments.map((payment) => (
                  <tr key={payment.id} className="hover:bg-slate-50/50 transition-colors">
                    <td className="px-6 py-5">
                      <div className="flex items-center gap-3">
                         <div className={`p-2 rounded-lg ${payment.status === 'PAID' ? 'bg-green-50 text-green-600' : 'bg-orange-50 text-orange-600'}`}>
                           <Calendar size={18} />
                         </div>
                         <span className="font-bold text-slate-800 text-base">{payment.month}</span>
                      </div>
                    </td>
                    <td className="px-6 py-5">
                      <span className="font-bold text-slate-900 font-outfit text-lg">₹{payment.amount}</span>
                    </td>
                    <td className="px-6 py-5">
                      {payment.status === "PAID" ? (
                        <div className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-green-100 text-green-700 rounded-lg text-xs font-bold w-fit">
                          <CheckCircle2 size={14} /> Paid
                        </div>
                      ) : (
                        <div className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-orange-100 text-orange-700 rounded-lg text-xs font-bold w-fit">
                          <Clock size={14} /> Pending
                        </div>
                      )}
                    </td>
                    <td className="px-6 py-5">
                       {payment.status === "PAID" ? (
                         <div className="text-xs">
                           <p className="font-semibold text-slate-700">{new Date(payment.paymentDate!).toLocaleDateString()}</p>
                           {payment.transactionId && <p className="text-slate-400 mt-0.5 font-mono">Ref: {payment.transactionId}</p>}
                         </div>
                       ) : (
                         <span className="text-xs text-slate-400 font-semibold uppercase tracking-wider">-</span>
                       )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
